# config.yaml
---
inventory:
       plugin: SimpleInventory
       options:
            host_file: 'hosts.yaml'
            group_file: 'groups.yaml'
            defaults_file: 'default.yaml'
runner:
       plugin: threaded
       options:
            num_workers: 2
