---

SW1:
  hostname: "192.168.13.191"
  username: "ali"
  password: "rezvani"
  groups:
    - cisco
    - switches
  data:
     hname: "SW1"
     ntp : "10.10.10.10"

R1:
  hostname: "192.168.13.192"
  username: "ali"
  password: "rezvani"
  groups:
    - cisco
    - routers
  data:
     hname: "R1"
  #   ntp : "10.10.10.1"

nexus1:
  hostname: "192.168.13.193"
  username: "ali"
  password: "rezvani"
  groups:
    - nexus    
  data:
     hname: "nexus1"
     ntp : "10.10.10.10"
     
fw1:
  hostname: 192.168.1.113
  username: admin
  password: admin
  port: 22
  platform: fortinet
  data:
      hname: "fw1"
      role: firewall
      type: ssh


    


